FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 6004
CMD ["uvicorn", "api.tagger:app", "--host", "0.0.0.0", "--port", "6004"]
