name: image-tagger

services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6060:6060"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Shanghai
      - TAG_API_URL=http://python-api:6004
    restart: unless-stopped

  python-api:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "6004:6004"
    volumes:
      - ./api:/app/api
      - ./config.yaml:/app/config.yaml
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
  web:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./web/auto-label/build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped

volumes:
  node_modules:
  mongodb_data:
  redis_data:
